stages:
  - prepare
  - build
  - deploy

image: docker:${DOCKER_VERSION}
variables:
  DOCKER_BUILDKIT: 1
  DOCKER_VERSION: 20.10.17

.docker_init_template:
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY

.ssh_init_template:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa

install:
  stage: prepare
  services:
    - name: docker:${DOCKER_VERSION}-dind
      command: ["--registry-mirror", "https://proxy-registry.skidstor.com"]
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
      policy: pull-push
  before_script:
    - !reference [.docker_init_template]
  script:
    - mkdir -p node_modules

    - >
      docker build
      --file docker/node/Dockerfile
      --target install
      --tag $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install
      .

    - rm -rf node_modules

    - docker create --name node $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install
    - docker cp node:/app/node_modules $CI_PROJECT_DIR/

.build_template:
  stage: build
  services:
    - name: docker:${DOCKER_VERSION}-dind
      command: ["--registry-mirror", "https://proxy-registry.skidstor.com"]
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
      policy: pull
    - key: next-cache-${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
      paths:
        - .next/cache
      policy: pull-push
  before_script:
    - !reference [.docker_init_template]
  script:
    - mkdir -p .next/cache

    - >
      docker build
      --file docker/node/Dockerfile
      --build-arg BUILDKIT_INLINE_CACHE=1
      --cache-from $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
      --target build
      --tag $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
      --build-arg NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
      --build-arg NEXT_PUBLIC_DATA_POLICY=$NEXT_PUBLIC_DATA_POLICY
      --build-arg NEXT_PUBLIC_TARIFFS=$NEXT_PUBLIC_TARIFFS
      --build-arg NEXT_PUBLIC_USER_AGREEMENT=$NEXT_PUBLIC_USER_AGREEMENT
      --build-arg NEXT_PUBLIC_CONTACT_EMAIL=$NEXT_PUBLIC_CONTACT_EMAIL
      --build-arg NEXT_PUBLIC_BOT_LINK=$NEXT_PUBLIC_BOT_LINK
      --build-arg NEXT_PUBLIC_TEXT_SECOND_CHECKBOX="$NEXT_PUBLIC_TEXT_SECOND_CHECKBOX"
      --build-arg NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES="$NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES"
      --build-arg NEXT_PUBLIC_COMPANY_NAME="$NEXT_PUBLIC_COMPANY_NAME"
      --build-arg NEXT_PUBLIC_COMPANY_INN=$NEXT_PUBLIC_COMPANY_INN
      --build-arg NEXT_PUBLIC_COMPANY_OGRNIP=$NEXT_PUBLIC_COMPANY_OGRNIP
      .

    - rm -rf .next/cache

    - docker create --name main_page $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
    - docker cp main_page:/app/.next/cache $CI_PROJECT_DIR/.next/cache

    - docker push $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME

.deploy_production_template:
  stage: deploy
  environment:
    name: production-${PROJECT_NAME}
  variables:
    COMPOSE_PROJECT_NAME: ${PROJECT_NAME}_main_page
    LANDING_IMAGE: $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
    DOCKER_HOST: $DEPLOY_PROD_DOCKER_HOST
  before_script:
    - !reference [.ssh_init_template]
    - !reference [.docker_init_template]
  script:
    - docker compose pull main_page

    - docker compose up -d --wait
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build_loverbotxyz:
  extends: .build_template
  variables:
    PROJECT_NAME: loverbotxyz
    NEXT_PUBLIC_BACKEND_URL: https://api.loverbot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/SJdrU5VCz1LBNQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Деревлев Александр Генадьевич
    NEXT_PUBLIC_COMPANY_INN: 101601117953
    NEXT_PUBLIC_COMPANY_OGRNIP: 322100000008640

build_healthyeatinglive:
  extends: .build_template
  variables:
    PROJECT_NAME: healthyeatinglive
    NEXT_PUBLIC_BACKEND_URL: https://api.healthyeating.live
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Деревлев Александр Генадьевич
    NEXT_PUBLIC_COMPANY_INN: 101601117953
    NEXT_PUBLIC_COMPANY_OGRNIP: 322100000008640

build_dietaquest:
  extends: .build_template
  variables:
    PROJECT_NAME: dietaquest
    NEXT_PUBLIC_BACKEND_URL: https://api.dieta.quest
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Деревлев Александр Генадьевич
    NEXT_PUBLIC_COMPANY_INN: 101601117953
    NEXT_PUBLIC_COMPANY_OGRNIP: 322100000008640

build_lovebotinfo:
  extends: .build_template
  variables:
    PROJECT_NAME: lovebotinfo
    NEXT_PUBLIC_BACKEND_URL: https://api.lovebot.info
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Деревлев Александр Генадьевич
    NEXT_PUBLIC_COMPANY_INN: 101601117953
    NEXT_PUBLIC_COMPANY_OGRNIP: 322100000008640

build_xlovebotxyz:
  extends: .build_template
  variables:
    PROJECT_NAME: xlovebotxyz
    NEXT_PUBLIC_BACKEND_URL: https://api.paylovebot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Жигульских Анастасия Сергеевна
    NEXT_PUBLIC_COMPANY_INN: 360601215399
    NEXT_PUBLIC_COMPANY_OGRNIP: 322366800070219


build_pay-love-botxyz:
  extends: .build_template
  variables:
    PROJECT_NAME: pay-love-botxyz
    NEXT_PUBLIC_BACKEND_URL: https://api.paylovebot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Жигульских Анастасия Сергеевна
    NEXT_PUBLIC_COMPANY_INN: 360601215399
    NEXT_PUBLIC_COMPANY_OGRNIP: 322366800070219

build_loverbotpayxyz:
  extends: .build_template
  variables:
    PROJECT_NAME: loverbotpayxyz
    NEXT_PUBLIC_BACKEND_URL: https://api.paylovebot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Жигульских Анастасия Сергеевна
    NEXT_PUBLIC_COMPANY_INN: 360601215399
    NEXT_PUBLIC_COMPANY_OGRNIP: 322366800070219

build_lovebotvkxyz:
  extends: .build_template
  variables:
    PROJECT_NAME: lovebotvkxyz
    NEXT_PUBLIC_BACKEND_URL: https://api.paylovebot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Жигульских Анастасия Сергеевна
    NEXT_PUBLIC_COMPANY_INN: 360601215399
    NEXT_PUBLIC_COMPANY_OGRNIP: 322366800070219

build_paylovebotxyz:
  extends: .build_template
  variables:
    PROJECT_NAME: paylovebotxyz
    NEXT_PUBLIC_BACKEND_URL: https://api.paylovebot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Жигульских Анастасия Сергеевна
    NEXT_PUBLIC_COMPANY_INN: 360601215399
    NEXT_PUBLIC_COMPANY_OGRNIP: 322366800070219

build_paylovebot1xyz:
  extends: .build_template
  variables:
    PROJECT_NAME: paylovebot1xyz
    NEXT_PUBLIC_BACKEND_URL: https://api.paylovebot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Алевская Ульяна Сергеевна
    NEXT_PUBLIC_COMPANY_INN: 190901248906
    NEXT_PUBLIC_COMPANY_OGRNIP: 322190000016507

build_loverbotingxyz:
  extends: .build_template
  variables:
    PROJECT_NAME: loverbotingxyz
    NEXT_PUBLIC_BACKEND_URL: https://api.paylovebot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Алевская Ульяна Сергеевна
    NEXT_PUBLIC_COMPANY_INN: 190901248906
    NEXT_PUBLIC_COMPANY_OGRNIP: 322190000016507

build_love-bot-vkxyz:
  extends: .build_template
  variables:
    PROJECT_NAME: love-bot-vkxyz
    NEXT_PUBLIC_BACKEND_URL: https://api.paylovebot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/bUsF6dPCCOXRdQ
    NEXT_PUBLIC_TARIFFS: https://disk.yandex.ru/i/KHlpQrqQ1ysYsg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/xV5k3dTUsrS1AQ
    NEXT_PUBLIC_CONTACT_EMAIL: promohelper@proton.me
    NEXT_PUBLIC_BOT_LINK: vk.me/lovescan
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного доступа. В дальнейшем, через 72 часа после получения пробного доступа, списывается 2890 рублей за каждый месяц использования сервиса.
    NEXT_PUBLIC_MAIN_PAGE_TEXT_SUBSCRIPTION_PRICES: Далее 2890 ₽ в месяц
    NEXT_PUBLIC_COMPANY_NAME: ИП Алевская Ульяна Сергеевна
    NEXT_PUBLIC_COMPANY_INN: 190901248906
    NEXT_PUBLIC_COMPANY_OGRNIP: 322190000016507

deploy_production_loverbotxyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: loverbotxyz
    VIRTUAL_HOST: loverbot.xyz

deploy_production_healthyeatinglive:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: healthyeatinglive
    VIRTUAL_HOST: healthyeating.live

deploy_production_dietaquest:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: dietaquest
    VIRTUAL_HOST: dieta.quest

deploy_production_lovebotinfo:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: lovebotinfo
    VIRTUAL_HOST: love-bot.info

deploy_production_xlovebotxyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: xlovebotxyz
    VIRTUAL_HOST: xlovebot.xyz

deploy_production_pay-love-botxyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: pay-love-botxyz
    VIRTUAL_HOST: pay-love-bot.xyz

deploy_production_loverbotpayxyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: loverbotpayxyz
    VIRTUAL_HOST: loverbotpay.xyz

deploy_production_lovebotvkxyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: lovebotvkxyz
    VIRTUAL_HOST: lovebotvk.xyz

deploy_production_paylovebotxyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: paylovebotxyz
    VIRTUAL_HOST: paylovebot.xyz

deploy_production_paylovebot1xyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: paylovebot1xyz
    VIRTUAL_HOST: paylovebot1.xyz

deploy_production_loverbotingxyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: loverbotingxyz
    VIRTUAL_HOST: lover-boting.xyz

deploy_production_love-bot-vkxyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: love-bot-vkxyz
    VIRTUAL_HOST: love-bot-vk.xyz
