stages:
  - build
  - deploy

image: docker:20.10.16
variables:
  DOCKER_BUILDKIT: 1

.docker_init_template:
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY

.ssh_init_template:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa

build:
  stage: build
  services:
    - name: docker:20.10.16-dind
      command: ["--registry-mirror", "https://proxy-registry.skidstor.com"]
  before_script:
    - !reference [ .docker_init_template ]
  script:
    - >
      docker build
      -f Dockerfile
      --cache-from $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME
      --build-arg BUILDKIT_INLINE_CACHE=1
      --tag $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME
      .

    - docker push $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME

deploy-loverbotxyz:
  stage: deploy
  environment:
    name: deploy-loverbotxyz
  variables:
    COMPOSE_PROJECT_NAME: loverbotxyz
    DOCKER_HOST: $DEPLOY_PROD_DOCKER_HOST
    VIRTUAL_HOST: loverbot.xyz
    NEXT_PUBLIC_BACKEND_URL: api.loverbot.xyz
  before_script:
    - !reference [ .ssh_init_template ]
    - !reference [ .docker_init_template ]
  script:
    - docker compose pull main_page

    - docker compose up -d --wait
  rules:
    - if: $CI_COMMIT_BRANCH == "main"