stages:
  - setup
  - build
  - deploy

image: docker:20.10.16
variables:
  DOCKER_BUILDKIT: 1

.docker_init_template:
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY

.ssh_init_template:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa

install:
  stage: setup
  services:
    - name: docker:20.10.16-dind
      command: ["--registry-mirror", "https://proxy-registry.skidstor.com"]
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
      policy: pull-push
  before_script:
    - !reference [.docker_init_template]
  script:
    - mkdir -p node_modules

    - >
      docker build
      --file docker/node/Dockerfile
      --build-arg BUILDKIT_INLINE_CACHE=1
      --cache-from $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install
      --target install
      --tag $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install
      .

    - docker create --name node $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install
    - docker cp node:/app/node_modules $CI_PROJECT_DIR/node

    - docker push $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install

.build_template:
  stage: build
  services:
    - name: docker:20.10.16-dind
      command: ["--registry-mirror", "https://proxy-registry.skidstor.com"]
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
      policy: pull
    - key: next-cache-${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
      paths:
        - .next/cache
      policy: pull-push
  #  variables:
  #    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/1r8-2eCe5WuQeg
  #    NEXT_PUBLIC_TARIFES: https://disk.yandex.ru/i/QkdXA0uC9keJnA
  #    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/MMr2_pXDMYtDTw
  before_script:
    - !reference [.docker_init_template]
  script:
    - ls -al
    - mkdir -p .next/cache

    - >
      docker build
      --file docker/node/Dockerfile
      --build-arg BUILDKIT_INLINE_CACHE=1
      --cache-from $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install
      --cache-from $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
      --target build
      --tag $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
      --build-arg NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
      --build-arg NEXT_PUBLIC_DATA_POLICY=$NEXT_PUBLIC_DATA_POLICY
      --build-arg NEXT_PUBLIC_TARIFES=$NEXT_PUBLIC_TARIFES
      --build-arg NEXT_PUBLIC_USER_AGREEMENT=$NEXT_PUBLIC_USER_AGREEMENT
      --build-arg NEXT_PUBLIC_CONTACT_EMAIL=$NEXT_PUBLIC_CONTACT_EMAIL
      --build-arg NEXT_PUBLIC_BOT_LINK=$NEXT_PUBLIC_BOT_LINK
      --build-arg NEXT_PUBLIC_REDIRECT_AFTER_PAYMENT=$NEXT_PUBLIC_REDIRECT_AFTER_PAYMENT
      --build-arg NEXT_PUBLIC_TEXT_SECOND_CHECKBOX="$NEXT_PUBLIC_TEXT_SECOND_CHECKBOX"
      .

    - docker create --name main_page $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
    - docker cp main_page:/app/.next/cache $CI_PROJECT_DIR/.next/cache

    - docker push $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME

.deploy_production_template:
  stage: deploy
  environment:
    name: production-${PROJECT_NAME}
  variables:
    COMPOSE_PROJECT_NAME: ${PROJECT_NAME}_main_page
    LANDING_IMAGE: $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
    DOCKER_HOST: $DEPLOY_PROD_DOCKER_HOST
  before_script:
    - !reference [.ssh_init_template]
    - !reference [.docker_init_template]
  script:
    - docker compose pull main_page

    - docker compose up -d --wait
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build_loverbotxyz:
  extends: .build_template
  variables:
    PROJECT_NAME: loverbotxyz
    NEXT_PUBLIC_BACKEND_URL: https://api.loverbot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/RqF9W6SnAzWXTw
    NEXT_PUBLIC_TARIFES: https://disk.yandex.ru/i/cC3KJKjkakQxOg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/SJdrU5VCz1LBNQ
    NEXT_PUBLIC_CONTACT_EMAIL: loverbot.xyz@proton.me
    NEXT_PUBLIC_BOT_LINK: https://vk.com/love____bot1
    NEXT_PUBLIC_REDIRECT_AFTER_PAYMENT: https://vk.me/love____bot1
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного журнала. В дальнейшем, через 6 часов после получения пробного журнала, списывается 1990 рублей за каждый месяц использования сервиса. В случае нехватки средств, мы переведем вас на тариф со списаниями по 1090 руб каждые две недели, по 590 руб каждую неделю и 190 руб за каждые сутки.

build_payloverbotxyz:
  extends: .build_template
  variables:
    PROJECT_NAME: payloverbotxyz
    NEXT_PUBLIC_BACKEND_URL: https://apipay.loverbot.xyz
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/i/RqF9W6SnAzWXTw
    NEXT_PUBLIC_TARIFES: https://disk.yandex.ru/i/cC3KJKjkakQxOg
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/SJdrU5VCz1LBNQ
    NEXT_PUBLIC_CONTACT_EMAIL: loverbot.xyz@proton.me
    NEXT_PUBLIC_BOT_LINK: https://vk.com/love____bot
    NEXT_PUBLIC_REDIRECT_AFTER_PAYMENT: https://vk.me/love____bot
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного журнала. В дальнейшем, через 6 часов после получения пробного журнала, списывается 1990 рублей за каждый месяц использования сервиса. В случае нехватки средств, мы переведем вас на тариф со списаниями по 1090 руб каждые две недели, по 590 руб каждую неделю и 190 руб за каждые сутки.

build_healthyeatinglive:
  extends: .build_template
  variables:
    PROJECT_NAME: healthyeatinglive
    NEXT_PUBLIC_BACKEND_URL: https://pay.healthyeating.live
    NEXT_PUBLIC_DATA_POLICY: https://disk.yandex.ru/d/EdydKBvu92YaQA
    NEXT_PUBLIC_TARIFES: https://disk.yandex.ru/i/KwXvd6da3oGspA
    NEXT_PUBLIC_USER_AGREEMENT: https://disk.yandex.ru/i/nYsZV9j8vMn21g
    NEXT_PUBLIC_CONTACT_EMAIL: loverbot.xyz@proton.me
    NEXT_PUBLIC_BOT_LINK: https://vk.com/love____bot2
    NEXT_PUBLIC_REDIRECT_AFTER_PAYMENT: https://vk.me/love____bot2
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: 1 рубль за получение пробного журнала. В дальнейшем, через 6 часов после получения пробного журнала, списывается 3290 рублей за каждый месяц использования сервиса. В случае нехватки средств, мы переведем вас на тариф со списаниями по 1690 руб каждые две недели, по 890 руб каждую неделю и 190 руб за каждые сутки.

deploy_production_loverbotxyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: loverbotxyz
    VIRTUAL_HOST: loverbot.xyz

deploy_production_payloverbotxyz:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: payloverbotxyz
    VIRTUAL_HOST: pay.loverbot.xyz

deploy_production_healthyeatinglive:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: healthyeatinglive
    VIRTUAL_HOST: healthyeating.live