version: "3.9"

services:
  main_page:
    image: registry.skidstor.com/lovebot1/main_page:main
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - PORT=80

networks:
  default:
    external:
      name: nginx-proxy
